package com.mochivated.brailleapp

/* Template
	VCharacter('',
		arrayOf(false, false,
				false, false,
				false, false)),
 */

val characterLists: Array<VCharacter> = arrayOf(
	//Letters
	VCharacter('a',
		arrayOf(true, false,
			false, false,
			false, false)),
	VCharacter('b',
		arrayOf(true, false,
			true, false,
			false, false)),
	VCharacter('c',
		arrayOf(true, true,
			false, false,
			false, false)),
	VCharacter('d',
		arrayOf(true, true,
			false, true,
			false, false)),
	VCharacter('e',
		arrayOf(true, false,
			false, true,
			false, false)),
	VCharacter('f',
		arrayOf(true, true,
			true, false,
			false, false)),
	VCharacter('g',
		arrayOf(true, true,
			true, true,
			false, false)),
	VCharacter('h',
		arrayOf(true, false,
			true, true,
			false, false)),
	VCharacter('i',
		arrayOf(false, true,
			true, false,
			false, false)),
	VCharacter('j',
		arrayOf(false, true,
			true, true,
			false, false)),
	VCharacter('k',
		arrayOf(true, false,
			false, false,
			true, false)),
	VCharacter('l',
		arrayOf(true, false,
			true, false,
			true, false)),
	VCharacter('m',
		arrayOf(true, true,
			false, false,
			true, false)),
	VCharacter('n',
		arrayOf(true, true,
			false, true,
			true, false)),
	VCharacter('o',
		arrayOf(true, false,
			false, true,
			true, false)),
	VCharacter('p',
		arrayOf(true, true,
			true, false,
			true, false)),
	VCharacter('q',
		arrayOf(true, true,
			true, true,
			true, false)),
	VCharacter('r',
		arrayOf(true, false,
			true, true,
			true, false)),
	VCharacter('s',
		arrayOf(false, true,
			true, false,
			true, false)),
	VCharacter('t',
		arrayOf(false, true,
			true, true,
			true, false)),
	VCharacter('u',
		arrayOf(true, false,
			false, false,
			true, true)),
	VCharacter('v',
		arrayOf(true, false,
			true, false,
			true, true)),
	VCharacter('w',
		arrayOf(false, true,
			true, true,
			false, true)),
	VCharacter('x',
		arrayOf(true, true,
			false, false,
			true, true)),
	VCharacter('y',
		arrayOf(true, true,
			false, true,
			true, true)),
	VCharacter('z',
		arrayOf(true, false,
			false, true,
			true, true)),
	
	//Numbers
	VCharacter('a',
		arrayOf(true, false,
			false, false,
			false, false)),
	VCharacter('b',
		arrayOf(true, false,
			true, false,
			false, false)),
	VCharacter('c',
		arrayOf(true, true,
			false, false,
			false, false)),
	VCharacter('d',
		arrayOf(true, true,
			false, true,
			false, false)),
	VCharacter('e',
		arrayOf(true, false,
			false, true,
			false, false)),
	VCharacter('f',
		arrayOf(true, true,
			true, false,
			false, false)),
	VCharacter('g',
		arrayOf(true, true,
			true, true,
			false, false)),
	VCharacter('h',
		arrayOf(true, false,
			true, true,
			false, false)),
	VCharacter('i',
		arrayOf(false, true,
			true, false,
			false, false)),
	VCharacter('j',
		arrayOf(false, true,
			true, true,
			false, false)),
	
	//Punctuation Signs

	
	//Composition Signs
)